#include "christmas_tree.h"
#include "led_params.h"

// (3-bit pixel color type) | (count - 1)
// count max = 32

static const uint8_t treeArch[] = {
  // 0 col
  M_TREE_CL_SPACE  | (30 - 1),
  M_TREE_CL_SNOW   | (4 - 1),
  // 1 col (reverse)
  M_TREE_CL_SPACE  | (1 - 1),
  M_TREE_CL_LIGHT0 | (2 - 1),
  M_TREE_CL_SPACE  | (27 - 1),
  // 2 col
  M_TREE_CL_SPACE  | (18 - 1),
  M_TREE_CL_LIGHT0 | (2 - 1),
  M_TREE_CL_SPACE  | (4 - 1),
  M_TREE_CL_BRANCH | (2 - 1),
  M_TREE_CL_LIGHT0 | (1 - 1),
  M_TREE_CL_SPACE  | (1 - 1),
  M_TREE_CL_SNOW   | (4 - 1),
  // 3 col (reverse)
  M_TREE_CL_SPACE  | (2 - 1),
  M_TREE_CL_BRANCH | (2 - 1),
  M_TREE_CL_SPACE  | (4 - 1),
  M_TREE_CL_LIGHT0 | (1 - 1),
  M_TREE_CL_BRANCH | (2 - 1),
  M_TREE_CL_SPACE  | (4 - 1),
  M_TREE_CL_LIGHT0 | (2 - 1),
  M_TREE_CL_SPACE  | (11 + 10 - 1),
  // 4 col
  M_TREE_CL_BRANCH | (2 - 1),
  M_TREE_CL_LIGHT0 | (1 - 1),
  M_TREE_CL_SPACE  | (3 - 1),
  M_TREE_CL_LIGHT0 | (1 - 1),
  M_TREE_CL_BRANCH | (2 - 1),
  M_TREE_CL_SPACE  | (4 - 1),
  M_TREE_CL_LIGHT0 | (1 - 1),
  M_TREE_CL_BRANCH | (2 - 1),
  M_TREE_CL_SPACE  | (2 - 1),
  M_TREE_CL_SNOW   | (4 - 1),
  // 5 col (reverse)
  M_TREE_CL_SPACE  | (2 - 1),
  M_TREE_CL_BRANCH | (4 - 1),
  M_TREE_CL_SPACE  | (4 - 1),
  M_TREE_CL_BRANCH | (3 - 1),
  M_TREE_CL_SPACE  | (3 - 1),
  M_TREE_CL_BRANCH | (3 - 1),
  M_TREE_CL_LIGHT0 | (1 - 1),
  M_TREE_CL_SPACE  | (8 + 6 - 1),
  // 6 col
  M_TREE_CL_LIGHT0 | (1 - 1),
  M_TREE_CL_BRANCH | (4 - 1),
  M_TREE_CL_SPACE  | (3 - 1),
  M_TREE_CL_LIGHT0 | (1 - 1),
  M_TREE_CL_BRANCH | (3 - 1),
  M_TREE_CL_SPACE  | (3 - 1),
  M_TREE_CL_LIGHT0 | (1 - 1),
  M_TREE_CL_BRANCH | (4 - 1),
  M_TREE_CL_SPACE  | (2 - 1),
  M_TREE_CL_SNOW   | (4 - 1),
  // 7 col (reverse)
  M_TREE_CL_SPACE  | (2 - 1),
  M_TREE_CL_BRANCH | (7 - 1),
  M_TREE_CL_SPACE  | (1 - 1),
  M_TREE_CL_BRANCH | (6 - 1),
  M_TREE_CL_SPACE  | (2 - 1),
  M_TREE_CL_BRANCH | (6 - 1),
  M_TREE_CL_SPACE  | (1 - 1),
  M_TREE_CL_LIGHT1 | (1 - 1),
  M_TREE_CL_SPACE  | (2 - 1),
  // 8 col
  M_TREE_CL_LIGHT1 | (2 - 1),
  M_TREE_CL_STEM   | (28 - 1),
  M_TREE_CL_SNOW   | (4 - 1),
  // 9 col (reverse), copy of 7
  M_TREE_CL_SPACE  | (2 - 1),
  M_TREE_CL_BRANCH | (7 - 1),
  M_TREE_CL_SPACE  | (1 - 1),
  M_TREE_CL_BRANCH | (6 - 1),
  M_TREE_CL_SPACE  | (2 - 1),
  M_TREE_CL_BRANCH | (6 - 1),
  M_TREE_CL_SPACE  | (1 - 1),
  M_TREE_CL_LIGHT1 | (1 - 1),
  M_TREE_CL_SPACE  | (2 + 6 - 1),
  // 10 col, copy of 6
  M_TREE_CL_LIGHT0 | (1 - 1),
  M_TREE_CL_BRANCH | (4 - 1),
  M_TREE_CL_SPACE  | (3 - 1),
  M_TREE_CL_LIGHT0 | (1 - 1),
  M_TREE_CL_BRANCH | (3 - 1),
  M_TREE_CL_SPACE  | (3 - 1),
  M_TREE_CL_LIGHT0 | (1 - 1),
  M_TREE_CL_BRANCH | (4 - 1),
  M_TREE_CL_SPACE  | (2 - 1),
  M_TREE_CL_SNOW   | (4 - 1),
  // 11 col (reverse), copy of 5
  M_TREE_CL_SPACE  | (2 - 1),
  M_TREE_CL_BRANCH | (4 - 1),
  M_TREE_CL_SPACE  | (4 - 1),
  M_TREE_CL_BRANCH | (3 - 1),
  M_TREE_CL_SPACE  | (3 - 1),
  M_TREE_CL_BRANCH | (3 - 1),
  M_TREE_CL_LIGHT0 | (1 - 1),
  M_TREE_CL_SPACE  | (8 + 10 - 1),
  // 12 col, copy of 4
  M_TREE_CL_BRANCH | (2 - 1),
  M_TREE_CL_LIGHT0 | (1 - 1),
  M_TREE_CL_SPACE  | (3 - 1),
  M_TREE_CL_LIGHT0 | (1 - 1),
  M_TREE_CL_BRANCH | (2 - 1),
  M_TREE_CL_SPACE  | (4 - 1),
  M_TREE_CL_LIGHT0 | (1 - 1),
  M_TREE_CL_BRANCH | (2 - 1),
  M_TREE_CL_SPACE  | (2 - 1),
  M_TREE_CL_SNOW   | (4 - 1),
  // 13 col (reverse), copy of 3
  M_TREE_CL_SPACE  | (2 - 1),
  M_TREE_CL_BRANCH | (2 - 1),
  M_TREE_CL_SPACE  | (4 - 1),
  M_TREE_CL_LIGHT0 | (1 - 1),
  M_TREE_CL_BRANCH | (2 - 1),
  M_TREE_CL_SPACE  | (4 - 1),
  M_TREE_CL_LIGHT0 | (2 - 1),
  M_TREE_CL_SPACE  | (11 + 18 - 1),
  // 14 col, copy of 2
  M_TREE_CL_LIGHT0 | (2 - 1),
  M_TREE_CL_SPACE  | (4 - 1),
  M_TREE_CL_BRANCH | (2 - 1),
  M_TREE_CL_LIGHT0 | (1 - 1),
  M_TREE_CL_SPACE  | (1 - 1),
  M_TREE_CL_SNOW   | (4 - 1),
  // 15 col (reverse), copy of 1
  M_TREE_CL_SPACE  | (1 - 1),
  M_TREE_CL_LIGHT0 | (2 - 1),
  M_TREE_CL_STOP
};